name: catclassification
channels:
  - defaults
dependencies:
  - _anaconda_depends=2019.03
  - pytorch=1.3.1
  - pip:
    - mlflow==1.5.0
    - pillow==6.2.1
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - torchvision==0.4.1